// import type { Metadata } from "next";
// import 'bootstrap/dist/css/bootstrap.min.css';
// // import 'bootstrap/dist/js/bootstrap.bundle.min.js';
// import BootstrapClient from "../../components/BootstrapClient";
// import "./globals.css";
// import HeadingBredcrum from "../../components/HeadingBredcrum";
// import { Toaster } from "react-hot-toast";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         {children}
//         <BootstrapClient/>
//         <Toaster position="top-right" />
//       </body>
//     </html>
//   );
// }
"use client";
import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import { useEffect } from "react";
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import BootstrapClient from "../../components/BootstrapClient";
import "./globals.css";
import HeadingBredcrum from "../../components/HeadingBredcrum";
import { Toaster } from "react-hot-toast";
// import { PermissionsProvider } from "..../../utils/context/PermissionsContext";  // Path to your context file
import { PermissionsProvider } from "../../utils/services/PermissionsContext";
import 'leaflet/dist/leaflet.css';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    if ("serviceWorker" in navigator) {
      navigator.serviceWorker
        .register("/firebase-messaging-sw.js")
        .then((registration) => console.log("Service Worker registered:", registration))
        .catch((error) => console.error("Service Worker registration failed:", error));
    }
  }, []);

  return (
    <html lang="en">
      <body>
        {/* Wrap the children with PermissionsProvider */}
        <PermissionsProvider>
          {children}
        </PermissionsProvider>
        <BootstrapClient />
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
